import axios from 'axios';
import Bus from '@/Bus';
export default {
    state:{
        shopTypeList:[],
        shopList:[],
        shopTypeInfo:{},
        shopInfo:{},
        shopTypeId:'',
        shopId:'',
        goodsTypeListByShop:[]
    },
    mutations:{
        CHANGE_SHOPTYPE(state,info){
            state.shopTypeList=info.shopTypeList;
        },
        CHANGE_SHOPLIST(state,info){
            if(info.shopList)
            state.shopList=info.shopList;
            else
            state.shopList=[]
            
        },
        CHANGE_TYPEINFO(state,info){
            state.shopTypeInfo=info.shopTypeInfo
        },
        CHANGE_SHOPINFO(state,info){
            state.shopInfo=info.shopInfo
        },
        CHANGE_SHOPTYPEID(state,id){
            state.shopTypeId=id
        },
        CHANGE_SHOPID(state,id){
            state.shopId=id
        }
    },
    actions:{
        addShopType({dispatch},{formdata,success}){
            axios({
                url:'/addShopType',
                data:formdata,
                method:'post',
                headers:{'Content-Type': 'multipart/form-data'}
            }).then((data)=>{
                dispatch('getShopType')
                success(false,data.msg)                   
            })
        },
        getShopType({commit}){
            axios.get('/getShopType').then((data)=>{
                commit('CHANGE_SHOPTYPE',data)
            })
        },
        deleteShopType({dispatch},{id,adminId}){
            axios.delete('/deleteShopType',{
                params:{
                    id,
                    adminId
                }
            }).then((data)=>{
                dispatch('getShopType')
            })
        },
        addShop({commit,dispatch},{formdata,success}){
            axios({
                url:'/addShop',
                method:"post",
                data:formdata,
                headers:{'Content-Type': 'multipart/form-data'}
            }).then((data)=>{
                commit('CHANGE_TYPEINFO',{});
                dispatch('getShop')
                success(false,data.msg)
            })
        },
        getShop({commit}){
            axios.get('/getShop').then((data)=>{
                commit('CHANGE_SHOPLIST',data)
            })
        },
        deleteShop({dispatch},{id,adminId,success,fail}){
            axios.delete('/deleteShop',{
                params:{id,
                    adminId
                }
            }).then((data)=>{
                if(data.ok===1){
                    dispatch('getShop');
                    success(data.msg);    
                }else{
                    dispatch('getShop');
                    fail(data.msg)
                }
            })
        },
        getShopTypeById({commit},{id,success}){
            axios.get('/getShopTypeById',{
                params:{id}
            }).then((data)=>{
                if(data.ok==1){
                    commit('CHANGE_TYPEINFO',data);
                    success(true)
                }
                
            })
        },
        updateShopType({dispatch},{formdata,success}){
            axios({
                url:'/updateShopType',
                method:'post',
                data:formdata,
                headers:{'Content-Type': 'multipart/form-data'}
            }).then((data)=>{
                dispatch('getShopType')
                success(false,data.msg)
            })
        },
        getShopById({commit},{id,success}){
            
                axios.get('/getShopById',{
                    params:{id}
                }).then((data)=>{
                    if(data.ok==1){
                        commit('CHANGE_SHOPINFO',data);
                        commit('CHANGE_SHOPTYPEID',data.shopInfo.shopTypeId)
                        success(true)
                    }
                })
        },
        updateShop({dispatch},{formdata,success}){
            axios({
                url:'/updateShop',
                method:'post',
                data:formdata,
                headers:{'Content-Type':'multipart/form-data'}
            }).then((data)=>{
                dispatch('getShop');
                success(false,data.msg)
            })
        },
        getMatchShop({commit},{matchShop,success}){
            axios.get("/getMatchShop",{
                params:{matchShop}
            }).then((data)=>{
                commit('CHANGE_SHOPLIST',data)
                success(data.msg)
            })
        }
    }
}