import axios from 'axios';
export default{
    state:{
        goodsTypeList:[],
        goodsTypeInfo:{},
        goodsTypeId:"",
        goodsTypeByShop:[],
        goodsList:[],
        goodsInfo:{}
    },
    mutations:{
        CHANGE_GOODSTYPE(state,info){
            state.goodsTypeList=info.goodsTypeList
        },
        CHANGE_GOODSTYPE_INFO(state,info){
            state.goodsTypeInfo=info.goodsTypeInfo
        },
        CHANGE_GOODSTYPE_ID(state,id){
            state.goodsTypeId=id;
        },
        CHANGE_GOODSTYPE_BYSHOP(state,info){
            state.goodsTypeByShop=info.goodsTypeByShop
        },
        CHANGE_GOODSLIST(state,info){
            state.goodsList=info.goodsList
        },
        CHANGE_GOODSINFO(state,info){
            state.goodsInfo=info.goodsInfo
        }
    },
    actions:{
        addGoodsType({dispatch},{formdata,success}){
            axios({
                url:'/addGoodsType',
                method:"post",
                data:formdata,
                headers:{"Content-Type":"multipart/form-data"}
            }).then((data)=>{
                dispatch('getGoodsType')
                success(false,data.msg)
            })
        },
        getGoodsType({commit}){
            axios.get("/getGoodsType").then((data)=>{
                commit("CHANGE_GOODSTYPE",data);
            })
        },
        deleteGoodType({dispatch},{id,adminId,success}){
            axios.get('/deleteGoodType',{
                params:{
                    id,
                    adminId
                }
            }).then((data)=>{
                success(data.msg);
                dispatch('getGoodsType')
            })
        },
        getGoodsTypeById({commit},{id,success}){
            axios.get('/getGoodsTypeById',{
                params:{
                    id
                }
            }).then((data)=>{
                commit("CHANGE_GOODSTYPE_INFO",data)
                success(true,data.goodsTypeInfo.shopId)
                // this.$store.shop.commit('CHANGE_SHOPID',data.shopId)
            })
        },
        updateGoodsType({dispatch},{formdata,success}){
            axios({
                url:"/updateGoodsType",
                method:"post",
                data:formdata,
                headers:{'Content-Type':'multipart/form-data'}
            }).then((data)=>{
                dispatch('getGoodsType');
                success(false,data.msg)
            })
        },
        getGoodsTypeByShop({commit},{id}){
            axios.get('/getGoodsTypeByShop',{
                params:{id}
            }).then((data)=>{
                commit('CHANGE_GOODSTYPE_BYSHOP',data)
            })
        },
        addGoods({dispatch},{formdata,success}){
            axios({
              url:'/addGoods',
              data:formdata,
              method:"post",
              headers:{'Content-Type':'multipart/form-data'}
            }).then((data)=>{
                dispatch('getGoodsList');
                success(false,data.msg)
            })
        },
        getGoodsList({commit}){
            axios.get('/getGoodsList').then((data)=>{
                commit('CHANGE_GOODSLIST',data)
            })

        },
        deleteGoods({dispatch},{id,adminId,success}){
            axios.get('/deleteGoods',{
                params:{
                    id,
                    adminId
                }
            }).then((data)=>{
                dispatch('getGoodsList');
                success(false,data.msg)
            })
        },
        getGoodsInfo({commit},{id}){
            axios.get('/getGoodsInfo',{
                params:{
                    id
                }
            }).then((data)=>{
                commit('CHANGE_GOODSINFO',data);
            })
        },

    }
}
