import axios from "axios";
import Bus from '@/Bus'
export default{
    state:{
        adminName:localStorage.adminName||"",
        adminId:localStorage.adminId||"",
        adminLogList:[],
        logTypeEnum:{},
        adminList:[],
        pageSum:1,
        pageIndex:1
    },
    mutations:{
        CHANGE_ADMININFO(state,info){
            state.adminId=localStorage.adminId=info.adminId;
            state.adminName=localStorage.adminName=info.adminName;
        },
        OUT_LOGIN(state){
            localStorage.clear();
            state.adminId=localStorage.adminId;
            state.adminPassWord=localStorage.adminPassWord;
            Bus.$message('退出成功')
        },
        CHANGE_ADMINLOG(state,info){
            state.adminLogList=info.adminLogList;
            state.pageSum=info.pageSum;
            state.pageIndex=info.pageIndex
            // console.log(state.pageSum)
        },
        GET_ADMINLIST(state,info){
            state.adminList=info.adminList
        }
    },
    actions:{
        login({commit},{adminName,adminPassWord,success,fail}){
            axios.post('/login',{
                adminName,
                adminPassWord
            }).then((data)=>{
                if(data.ok===1){
                    commit('CHANGE_ADMININFO',data);
                    success(data.msg)
                }else{
                    fail(data.msg)
                }
            })
        },
        getAdminLogList({commit,state}){
            axios.get('/getAdminLogList',{
                params:{
                    pageIndex:state.pageIndex
                }
                }).then((data)=>{
                commit('CHANGE_ADMINLOG',data);
                // console.log(state.adminLogList)
            })
        },
        deletaAdminLog({dispatch},{id}){
            axios.get('/deletaAdminLog',{
                params:{
                    id
                }
            }).then(() => {
                    dispatch('getAdminLogList');
                })
        },
        updateAdminPassWord({commit},{adminId,passWord,newPassWord,success,fail}){
            axios.post('/updateAdminPassWord',{
                adminId,
                passWord,
                newPassWord
            }).then((data)=>{
                if(data.ok===1){
                    commit('OUT_LOGIN')
                    success(data.msg)
                }else{
                    fail(data.msg)
                }
                
            })
        },
        getAdminList({commit}){
            axios.get('/getAdminList').then((data)=>{
                commit('GET_ADMINLIST',data)
            })
        },
        addAdmin({dispatch},{adminName,adminPassWord,success,fail}){
            axios.post('/addAdmin',{
                adminName,
                adminPassWord
            }).then((data)=>{
                if(data.ok==1){
                    success(data.msg)
                    dispatch('getAdminList')
                }else{
                    fail(data.msg)
                }
            })
        }
    }
}